Feat/reset password via email
Chagul/copains-de-route-back pull request #35
Opened 2024-01-05 21:26 UTC by nassksr

2024-01-05 21:49 UTC, TheLucas59 requested changes

2024-01-05 21:49 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/repository/UserRepository.java
> +    User findByEmail(String email);
Retourne un 
```suggestion
    Optional<User> findByEmail(String email);
```

2024-01-05 21:49 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/service/UserService.java
> +        }
Avec Optional tu pourras directement faire 
```suggestion
        User user = userRepository.findByEmail(email).orElseThrow(UserNotFoundException::new);
```

2024-01-05 21:49 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/service/UserService.java
> +        message.setFrom("ksrnass1208@gmail.com");
On va peut-être mettre l'adresse copains de route du coup non ?

2024-01-05 21:49 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/repository/UserTokenRepository.java
> +    UserToken findByToken(String token);
Même chose return un Optional

2024-01-05 21:49 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/service/UserService.java
> +        String resetLink = "http://localhost:8080/users/reset-password?token=" + token;
Faut pas return une url sur localhost mais du coup je me demande si on met en dur l'url du back déployé

2024-01-05 21:49 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/service/UserService.java
> +        }
Même chose avec l'optional tu pourras throw directement plutot qu'un if(null)

2024-01-05 21:49 UTC, TheLucas59 commented on src/main/resources/application.properties
> +spring.mail.password=gqwtedktpfjomelo
Voir pour setup l'adresse mail de copains de route du coup

2024-01-05 21:49 UTC, TheLucas59 commented on src/main/resources/templates/Password.html
> +<html lang="en">
fr

2024-01-05 21:49 UTC, TheLucas59 commented on src/main/resources/templates/PasswordsDontMatch.html
> +<html lang="en">
fr

2024-01-05 21:49 UTC, TheLucas59 commented on src/main/resources/templates/ResetPasswordSuccess.html
> +<html lang="en">
fr

2024-01-05 21:49 UTC, TheLucas59 commented on src/main/resources/templates/TokenNotFound.html
> +<html lang="en">
fr

2024-01-05 21:49 UTC, TheLucas59 commented on src/main/resources/templates/UrlExpired.html
> +<html lang="en">
fr

2024-01-05 21:49 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/controller/UserController.java
> +            return new ModelAndView("TokenNotFound");
On peut peut-être mettre UrlExpired aussi dans ce cas là, ce sera plus clair comme message pour un user

2024-01-05 21:51 UTC, TheLucas59 commented on src/main/resources/application.properties
> +spring.mail.password=gqwtedktpfjomelo
Peut être mettre le password pour les mail en secret sur google cloud ?

2024-01-05 22:23 UTC, nassksr commented on src/main/java/com/univ/lille/copainsderoute/platine/service/UserService.java
> +        message.setFrom("ksrnass1208@gmail.com");
yess

2024-01-05 22:25 UTC, nassksr commented on src/main/java/com/univ/lille/copainsderoute/platine/service/UserService.java
> +        String resetLink = "http://localhost:8080/users/reset-password?token=" + token;
j'ai mis localhost juste pour test mais je pense faudra l'url du back déployé pour le front et l'appli en general

2024-01-05 22:30 UTC, Chagul requested changes

2024-01-05 22:30 UTC, Chagul commented on src/main/java/com/univ/lille/copainsderoute/platine/controller/UserController.java
> +        userService.initiatePasswordReset(email);
`    public ResponseEntity<?> sendEmail((HttpServletRequest request, @PathVariable("email") String email) throws UserNotFoundException {
String baseUrl = ServletUriComponentsBuilder.fromRequestUri(request)
        .replacePath(null)
        .build()
        .toUriString();
        userService.initiatePasswordReset(email, baseUrl);`
        Et à faire suivre dans la chaine comme ça que ce soit localhost ou déployé ça renvoie l'url du back

2024-01-05 22:30 UTC, Chagul commented on src/main/java/com/univ/lille/copainsderoute/platine/service/UserService.java
> +        message.setFrom("ksrnass1208@gmail.com");
+1

2024-01-05 22:30 UTC, Chagul commented on src/main/resources/application.properties
> +spring.mail.password=gqwtedktpfjomelo
Setup de mon côté, pour le local remplacer par des variables d'environnement

2024-01-05 23:33 UTC, TheLucas59 commented on src/main/resources/application.properties
> +spring.mail.password=yuzmgvnwuwxkdxmy
Du coup tu peux l'enlever du properties, on le mettra en secret gcloud

2024-01-05 23:33 UTC, TheLucas59 approved these changes

2024-01-06 15:28 UTC, Chagul approved these changes

2024-01-06 15:37 UTC, merged