Feat/events near the loc
Chagul/copains-de-route-back pull request #9
Opened 2023-11-30 21:06 UTC by nassksr

2023-11-30 21:21 UTC, Chagul commented on src/main/java/com/univ/lille/copainsderoute/platine/controller/EventController.java
> +            @PathVariable("northeastLatitude") Double northeastLatitude,
le passer dans un body ça posera moins de probleme je pense, en le mettant dans l'url ça peut break avec les caractéres des longiture latitude

2023-11-30 21:21 UTC, Chagul commented on src/main/java/com/univ/lille/copainsderoute/platine/dtos/GpsCoordinatesDTOs.java
> +public class GpsCoordinatesDTOs {
Peut être utiliser le DTO directement dans l'appel API ? Voir https://stackoverflow.com/questions/73201089/how-to-use-requestparam-with-dto

2023-11-30 21:21 UTC, Chagul commented on src/main/java/com/univ/lille/copainsderoute/platine/entity/Event.java
> +    private List<Itinerary> itineraryPoints = new ArrayList<>();
C'est une liste de point ou d'itinéraire au final ?

2023-11-30 21:21 UTC, Chagul commented on src/main/java/com/univ/lille/copainsderoute/platine/service/EventService.java
> +                boolean isInside = this.isInside(gpsCoordinatesDTOs, itinerary.getLatitude(), itinerary.getLongitude());
Je pense tu peux le faire directement en SQL, ça sera moins lourd s'il y a 45k évenements, dans le répo en SRA j'avais fais un truc du genre :
 List<OperationMarketingCondition> findByStartDateLessThanEqualAndEndDateGreaterThanEqual(java.sql.Date nowDate, java.sql.Date nowDatee);
Tu peux regarder https://www.baeldung.com/spring-data-derived-queries pour plus d'info

2023-11-30 21:21 UTC, Chagul commented on src/main/java/com/univ/lille/copainsderoute/platine/service/EventService.java
> +
Je viens de voir ça, si jamais c'est trop compliqué à faire ce que j'ai dis dans le commentaire d'avant, tu peux laisser comme ça pour le moment

2023-11-30 21:22 UTC, TheLucas59 requested changes

2023-11-30 21:22 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/controller/EventController.java
> +        GpsCoordinatesDTOs gpsCoordinatesDTOs = new GpsCoordinatesDTOs(northeastLatitude, northeastLongitude, southwestLatitude, southwestLongitude, northwestLatitude, northwestLongitude, southeastLa
Pourquoi ne pas mettre le DTO en paramètres de la méthode ? comme ça il est mappé direct et il faut juste mettre les données dans le body a la place

```suggestion
    public ResponseEntity<List<Event>> getEventsByLocation(@RequestBody GpsCoordinateDTO gpsCoordinates)
```

2023-11-30 21:22 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/service/EventService.java
> +            List<Event> events = eventRepository.findAll();
Tu es obligée de tout récupérer ? Parce que si tu as 50 millions d'événements ça va être long

Peut être filtrer déjà par rapport à la date du jour pour qu'on ait que les événements pas encore passés

2023-11-30 21:22 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/service/EventService.java
> +            List<Event> eventsByLocation = new ArrayList<Event>();
DIAMOND OPERATOR

```suggestion
            List<Event> eventsByLocation = new ArrayList<>();
```

2023-11-30 21:22 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/service/EventService.java
> +        }
Indentation et lignes vides

2023-12-02 09:47 UTC, nassksr commented on src/main/java/com/univ/lille/copainsderoute/platine/controller/EventController.java
> +            @PathVariable("northeastLatitude") Double northeastLatitude,
je peux passer en body des params pour un get malheureusement

2023-12-02 12:31 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/controller/EventController.java
> +            @PathVariable("northeastLatitude") Double northeastLatitude,
Tu peux pas utiliser @RequestBodyParam ou quelque chose comme ça dans ta signature de méthode ?

2023-12-02 15:55 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/controller/EventController.java
> +            @PathVariable("northeastLatitude") Double northeastLatitude,
Enfin même juste @RequestBody comme un post

2023-12-03 00:10 UTC, Chagul reviewed
A quoi sert le controller et service point ?

2023-12-03 13:58 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/controller/ItineraryPointController.java
> +public class ItineraryPointController {
Pas sûr que ce soit spécialement utile, on devrait passer l'itinéraire a la création de l'événement

2023-12-03 13:58 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/dtos/dtoResponse/EventResponseDTOs.java
> +        }
Pas possible de faire juste 
```suggestion
this.comments = event.getComments();
```
?

2023-12-03 13:58 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/entity/Event.java
> +    private List<String> comments = new ArrayList<>();
```suggestion
List<Comments> comments = new ArrayList<>();
```

Non ?

2023-12-03 13:58 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/service/EventService.java
> +        promoter.setNumberEventsCreated(promoter.getNumberEventsCreated() + 1);
Il faut save aussi le user du coup

2023-12-03 13:58 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/service/EventService.java
>              if (evt == null) {
```suggestion
if(evt.isPresent())
```
Un optional sera jamais nul, c'est fait pour ça

2023-12-03 13:58 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/service/EventService.java
> +                List<ItineraryPoint> itineraries = eventRepository.findById(event.getId()).get().getItineraryPoints();
Fais gaffe au .get() sur les optional, si il est vide tu vas te taper des méchantes NPE

2023-12-03 16:53 UTC, nassksr commented on src/main/java/com/univ/lille/copainsderoute/platine/service/EventService.java
> +        promoter.setNumberEventsCreated(promoter.getNumberEventsCreated() + 1);
quand tu crée un event t'as aucun participant du coup ya que le promoter qui est enregistré comme organisateur ensuite les gens pourront rejoindr l'event, la liste des participants est vide au début

2023-12-03 16:56 UTC, nassksr commented on src/main/java/com/univ/lille/copainsderoute/platine/service/EventService.java
> +                List<ItineraryPoint> itineraries = eventRepository.findById(event.getId()).get().getItineraryPoints();
Bien vu

2023-12-04 13:21 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/service/CommentService.java
> +        }
Peut être séparer la modification du contenu de l'ajout ou retrait d'un like

2023-12-05 10:44 UTC, TheLucas59 approved these changes

2023-12-05 10:44 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/dtos/dtoResponse/UserResponseDTOs.java
> +        this.participatedEvent_id = participatedEvent_id;
On a juste besoin du nombre comme vu ensemble

2023-12-05 10:44 UTC, TheLucas59 commented on src/main/java/com/univ/lille/copainsderoute/platine/service/UserService.java
> +                }
A retirer du coup

2023-12-05 10:44 UTC, TheLucas59 commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
Mettre une variable d'environnement comme vu avec Aurel

2023-12-05 10:53 UTC, merged